---
title: "links"
---


# me elsewhere online
* [Software Sustainability Institute](https://software.ac.uk/about/fellows/david-wilby)
* [Google Scholar](https://scholar.google.com/citations?user=4kAyVwMAAAAJ)
* [My GitHub Profile](https://github.com/davidwyld)
* <a rel="me" href="https://fosstodon.org/@davidwilby">Mastodon</a>

# resources
* [Research Software Methods Lecture for Undergrads](https://github.com/davidwyld/ResearchSoftwareMethods) - [*video*](https://rse.shef.ac.uk/blog/2021-05-25-methods-ug-talk/)
* [Git & GitHub through GitKraken - Zero to Hero](https://github.com/RSE-Sheffield/git-github-zero-to-hero) - course developed by @[annakrystalli](https://github.com/annakrystalli/)

# blogs

+ [Reproducible MATLAB Blog](https://reproduciblematlab.github.io/blog/)
  + [A concise guide to reproducible MATLAB projects](https://reproduciblematlab.github.io/blog/posts/2022-concise-guide/) (also published on the [Software Sustainability Institute](https://software.ac.uk/blog/2022-07-06-concise-guide-reproducible-matlab-projects) and [RSE Sheffield](https://rse.shef.ac.uk/blog/2022-05-05-concise-guide-to-reproducible-matlab/) blogs)
  + [Can MATLAB projects ever be reproducible?](https://reproduciblematlab.github.io/blog/posts/2023-07-10-can-matlab-be-reproducible/)
  + [Reproducible MATLAB: what do the people want?](https://reproduciblematlab.github.io/blog/posts/2023-05-02-survey/)
+ [RSE Sheffield Blog](https://rse.shef.ac.uk/blog/)
  + [Demonstrating Importance and Value in Research Software](https://rse.shef.ac.uk/blog/2022-10-13-quality-value-research-software/)
  + [Software best practice: what can it do for me/my research?](https://rse.shef.ac.uk/blog/2019-best-practice/)
  + [Writing better and more shareable code](https://rse.shef.ac.uk/blog/2022-10-20-better-code/)
  + [Handy tools for git(s)](https://rse.shef.ac.uk/blog/2022-08-18-git-tools/)


# talks

+ *FAIR Research Software* - Open Research Conversations x LunchBytes, University of Sheffield, 2023. [[Slides](https://davidwilby.dev/opensourcefair4rs), [Repo](https://github.com/davidwilby/opensourcefair4rs), [Video](https://doi.org/10.15131/shef.data.24756393.v1)]
+ *Making MATLAB projects reproducible and shareable* - OpenFest, University of Sheffield, 2022. [[Slides](https://www.davidwilby.dev/reproducible_matlab/openfest2022/#/title-slide), [Repo](https://github.com/davidwilby/reproducible_matlab), [Video](https://figshare.shef.ac.uk/articles/media/Open_Research_in_Practice_2_OpenFest_session_recording_/21286449)]
+ Guest lecture for Computer Science Undergrads on RSE Methods, 2021-23. [[Slides](https://www.davidwilby.dev/ResearchSoftwareMethods/#/title-slide), [Previous versions](https://github.com/davidwilby/ResearchSoftwareMethods/releases)]

